package commands

import (
	"bytes"
	"errors"
	"flag"
	"fmt"
	"io"
	"io/fs"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"github.com/bogie-go/bogie/internal/scaffold"
	"github.com/bogie-go/bogie/templates"
)

const updateUsage = `Usage: bogie app:update [--pretend]

Moves the app to this Bogie's layout, as rails app:update does, but as a
three-way merge: bogie.toml records the version that generated the app, so
what that version generated (base) is rendered again, what this version
generates (theirs) is rendered, and each file on disk (ours, with your
edits) is merged with git merge-file. A file you never touched updates
silently; a file you edited where the template did not merges cleanly; only
a real overlap leaves conflict markers, and the report names those files.

Refuses on a dirty git tree, so the result is one reviewable diff. Files the
templates never produced are not touched: everything bogie g and you wrote
is safe by construction. Afterwards bogie.toml records the new version,
go mod tidy runs, and bogie doctor checks the markers.

  --pretend   the report only; nothing written
`

// Settings is what bogie.toml records.
type Settings struct {
	Version string
	Name    string
	Module  string
	Jobs    bool
}

// readSettings parses bogie.toml. The file is four lines the tool wrote
// itself, so this reads exactly that shape and nothing more.
func readSettings(root string) (Settings, error) {
	b, err := os.ReadFile(filepath.Join(root, Marker))
	if err != nil {
		return Settings{}, err
	}
	var s Settings
	for _, line := range strings.Split(string(b), "\n") {
		key, value, ok := strings.Cut(line, "=")
		if !ok || strings.HasPrefix(strings.TrimSpace(line), "#") {
			continue
		}
		key, value = strings.TrimSpace(key), strings.Trim(strings.TrimSpace(value), `"`)
		switch key {
		case "bogie":
			s.Version = value
		case "name":
			s.Name = value
		case "module":
			s.Module = value
		case "jobs":
			s.Jobs = value == "true"
		}
	}
	if s.Version == "" || s.Name == "" || s.Module == "" {
		return s, fmt.Errorf("%s: missing bogie, name or module; the file is written by `bogie new` and read as is", Marker)
	}
	return s, nil
}

// notMerged are files app:update never merges. go.mod and go.sum are
// tidied rather than merged, since `go mod tidy` adds what the new
// templates import and the recorded versions are the app's own; the marker
// is rewritten, not merged; and the credentials file and its key are made
// by `new` outside the templates, with a random key, so the old version's
// render of them is noise.
var notMerged = map[string]bool{
	"go.mod": true, "go.sum": true, Marker: true,
	"config/master.key": true, "config/credentials.yml.enc": true,
}

// Update handles `bogie app:update`.
func Update(args []string, out io.Writer) error {
	say := func(format string, a ...any) { _, _ = fmt.Fprintf(out, format, a...) }
	fs := flag.NewFlagSet("app:update", flag.ContinueOnError)
	fs.SetOutput(out)
	pretend := fs.Bool("pretend", false, "report what would change and write nothing")
	fs.Usage = func() { say(updateUsage) }
	if err := fs.Parse(args); err != nil {
		return err
	}
	root, err := appRoot(".")
	if err != nil {
		return err
	}
	settings, err := readSettings(root)
	if err != nil {
		return fmt.Errorf("app:update: %w", err)
	}
	current := Version()
	if settings.Version == current {
		say("%12s  %s was generated by this Bogie (%s); nothing to update\n", "identical", settings.Name, current)
		return nil
	}
	if !*pretend {
		if dirty, err := gitDirty(root); err == nil && dirty {
			return fmt.Errorf("app:update: the git tree has uncommitted changes; commit or stash them so the update is one reviewable diff (or --pretend)")
		}
	}

	// theirs: this version's templates, rendered as `new` would.
	theirsDir, err := os.MkdirTemp("", "bogie-theirs-")
	if err != nil {
		return err
	}
	defer func() { _ = os.RemoveAll(theirsDir) }()
	vars := scaffold.Vars{
		Name:          settings.Name,
		Module:        settings.Module,
		EnvPrefix:     strings.ToUpper(settings.Name),
		LayoutVersion: current,
		Jobs:          settings.Jobs,
		Mascot:        templates.MascotDataURI(),
	}
	if _, err := scaffold.Render(templates.App, "app", theirsDir, vars, scaffold.Options{}); err != nil {
		return fmt.Errorf("app:update: render: %w", err)
	}
	theirs, err := readTree(theirsDir)
	if err != nil {
		return err
	}

	// base: what the recorded version generated, from the module proxy.
	say("%12s  go run github.com/bogie-go/bogie@%s new %s\n", "run", settings.Version, settings.Name)
	base, baseErr := renderBase(settings, out)
	if baseErr != nil {
		say("%12s  %v\n", "note", baseErr)
		say("%12s  no base to merge against; this is a two-way report and nothing is written\n", "note")
	}

	ours, err := readTree(root)
	if err != nil {
		return err
	}
	results, err := merge(ours, base, theirs, settings.Version, current)
	if err != nil {
		return fmt.Errorf("app:update: %w", err)
	}

	write := !*pretend && baseErr == nil
	conflicts := 0
	for _, r := range results {
		say("%12s  %s\n", r.op, r.path)
		if r.op == opConflict {
			conflicts++
		}
		if !write || r.content == nil {
			continue
		}
		abs := filepath.Join(root, filepath.FromSlash(r.path))
		if err := os.MkdirAll(filepath.Dir(abs), 0o755); err != nil {
			return err
		}
		mode := os.FileMode(0o644)
		if strings.HasPrefix(r.path, "bin/") {
			mode = 0o755
		}
		if err := os.WriteFile(abs, r.content, mode); err != nil {
			return err
		}
	}
	if !write {
		if baseErr != nil {
			return fmt.Errorf("app:update: could not render what %s generated", settings.Version)
		}
		return nil
	}

	// The marker records the new version; go.mod is tidied, which adds what
	// the new templates import; doctor says whether the markers survived.
	if err := rewriteVersion(root, current); err != nil {
		return err
	}
	say("%12s  %s: bogie = %q\n", "updated", Marker, current)
	say("%12s  go mod tidy\n", "run")
	cmd := exec.Command("go", "mod", "tidy")
	cmd.Dir = root
	cmd.Stdout = out
	cmd.Stderr = os.Stderr
	if err := cmd.Run(); err != nil {
		return fmt.Errorf("app:update: go mod tidy: %w", err)
	}
	if conflicts > 0 {
		say("\n%d file(s) have conflict markers; resolve them, then run bogie doctor and bin/ci.\n", conflicts)
		return fmt.Errorf("app:update: %d conflict(s)", conflicts)
	}
	say("\n")
	return Doctor(out)
}

// renderBase runs the recorded version's `new` into a temp dir and reads
// the tree it made. Any pushed commit is a version the module proxy can
// serve, so a development build's apps can update too; a +dirty build's
// cannot, and says so.
func renderBase(s Settings, out io.Writer) (map[string][]byte, error) {
	if strings.Contains(s.Version, "dirty") {
		return nil, fmt.Errorf("%s was built from uncommitted changes, which no module proxy can serve", s.Version)
	}
	dir, err := os.MkdirTemp("", "bogie-base-")
	if err != nil {
		return nil, err
	}
	defer func() { _ = os.RemoveAll(dir) }()
	args := []string{"run", "github.com/bogie-go/bogie@" + s.Version, "new", s.Name, "--module=" + s.Module, "--skip-tidy"}
	if s.Jobs {
		args = append(args, "--jobs")
	}
	cmd := exec.Command("go", args...)
	cmd.Dir = dir
	var stderr bytes.Buffer
	cmd.Stdout = io.Discard
	cmd.Stderr = &stderr
	if err := cmd.Run(); err != nil {
		msg := strings.TrimSpace(stderr.String())
		if i := strings.LastIndex(msg, "\n"); i >= 0 {
			msg = msg[i+1:]
		}
		return nil, fmt.Errorf("go run bogie@%s: %s", s.Version, msg)
	}
	return readTree(filepath.Join(dir, s.Name))
}

// readTree reads every file under root into a map by slash path, skipping
// .git and build output, which no template produces.
func readTree(root string) (map[string][]byte, error) {
	out := map[string][]byte{}
	err := filepath.WalkDir(root, func(p string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		rel, _ := filepath.Rel(root, p)
		rel = filepath.ToSlash(rel)
		if d.IsDir() {
			if rel == ".git" || rel == "tmp" {
				return filepath.SkipDir
			}
			return nil
		}
		b, err := os.ReadFile(p)
		if err != nil {
			return err
		}
		out[rel] = b
		return nil
	})
	return out, err
}

type op string

const (
	opIdentical op = "identical" // ours already is theirs
	opUpdated   op = "updated"   // ours was base; now theirs
	opMerged    op = "merged"    // ours and theirs both changed, cleanly
	opConflict  op = "conflict"  // both changed the same lines; markers left
	opCreate    op = "create"    // new in this version
	opKept      op = "kept"      // the template changed nothing, or you deleted the file
	opRetired   op = "retired"   // no longer generated; left as it is
)

type result struct {
	path    string
	op      op
	content []byte // what to write, or nil for nothing
}

// merge decides every template-produced file. With no base (nil), the
// report is two-way: identical or conflict, and nothing is written.
func merge(ours, base, theirs map[string][]byte, oldVersion, newVersion string) ([]result, error) {
	paths := map[string]bool{}
	for p := range theirs {
		paths[p] = true
	}
	for p := range base {
		paths[p] = true
	}
	var sorted []string
	for p := range paths {
		if !notMerged[p] {
			sorted = append(sorted, p)
		}
	}
	sortStrings(sorted)

	var results []result
	for _, p := range sorted {
		o, inOurs := ours[p]
		b, inBase := base[p]
		t, inTheirs := theirs[p]
		switch {
		case !inTheirs:
			// The template is gone. The file is the user's now.
			results = append(results, result{p, opRetired, nil})
		case !inOurs && inBase:
			// Generated before and deleted by the user, like welcome.go.
			results = append(results, result{p, opKept, nil})
		case !inOurs:
			results = append(results, result{p, opCreate, t})
		case bytes.Equal(o, t):
			results = append(results, result{p, opIdentical, nil})
		case base == nil:
			results = append(results, result{p, opConflict, nil})
		case !inBase:
			// Old base had no such file but ours does: the user made one of
			// the same name. Theirs can only be offered as a conflict.
			merged, n, err := mergeFile(o, nil, t, oldVersion, newVersion)
			if err != nil {
				return nil, err
			}
			_ = n
			results = append(results, result{p, opConflict, merged})
		case bytes.Equal(o, b):
			results = append(results, result{p, opUpdated, t})
		case bytes.Equal(b, t):
			results = append(results, result{p, opKept, nil})
		default:
			merged, conflicts, err := mergeFile(o, b, t, oldVersion, newVersion)
			if err != nil {
				return nil, err
			}
			if conflicts > 0 {
				results = append(results, result{p, opConflict, merged})
			} else {
				results = append(results, result{p, opMerged, merged})
			}
		}
	}
	return results, nil
}

// mergeFile is `git merge-file -p ours base theirs`: the merged text, and
// how many conflict hunks it left.
func mergeFile(ours, base, theirs []byte, oldVersion, newVersion string) ([]byte, int, error) {
	dir, err := os.MkdirTemp("", "bogie-merge-")
	if err != nil {
		return nil, 0, err
	}
	defer func() { _ = os.RemoveAll(dir) }()
	paths := []string{filepath.Join(dir, "ours"), filepath.Join(dir, "base"), filepath.Join(dir, "theirs")}
	for i, content := range [][]byte{ours, base, theirs} {
		if content == nil {
			content = []byte{}
		}
		if err := os.WriteFile(paths[i], content, 0o644); err != nil {
			return nil, 0, err
		}
	}
	cmd := exec.Command("git", "merge-file", "-p",
		"-L", "yours", "-L", "bogie "+oldVersion, "-L", "bogie "+newVersion,
		paths[0], paths[1], paths[2])
	var stdout, stderr bytes.Buffer
	cmd.Stdout, cmd.Stderr = &stdout, &stderr
	err = cmd.Run()
	var exitErr *exec.ExitError
	switch {
	case err == nil:
		return stdout.Bytes(), 0, nil
	case errors.As(err, &exitErr) && exitErr.ExitCode() > 0:
		// A positive exit status is the number of conflicts.
		return stdout.Bytes(), exitErr.ExitCode(), nil
	default:
		return nil, 0, fmt.Errorf("git merge-file: %v: %s", err, strings.TrimSpace(stderr.String()))
	}
}

// rewriteVersion sets the bogie line of the marker to the new version.
func rewriteVersion(root, version string) error {
	path := filepath.Join(root, Marker)
	b, err := os.ReadFile(path)
	if err != nil {
		return err
	}
	lines := strings.Split(string(b), "\n")
	for i, l := range lines {
		if strings.HasPrefix(strings.TrimSpace(l), "bogie ") || strings.HasPrefix(strings.TrimSpace(l), "bogie=") {
			lines[i] = fmt.Sprintf("bogie = %q", version)
		}
	}
	return os.WriteFile(path, []byte(strings.Join(lines, "\n")), 0o644)
}

// gitDirty reports whether the app's git tree has uncommitted changes. An
// app that is not a git repository is never dirty.
func gitDirty(root string) (bool, error) {
	cmd := exec.Command("git", "status", "--porcelain")
	cmd.Dir = root
	out, err := cmd.Output()
	if err != nil {
		return false, err
	}
	return len(bytes.TrimSpace(out)) > 0, nil
}

func sortStrings(s []string) {
	for i := 1; i < len(s); i++ {
		for j := i; j > 0 && s[j] < s[j-1]; j-- {
			s[j], s[j-1] = s[j-1], s[j]
		}
	}
}
